services:
  # El Bridge personalizado
  airdcpp-bridge:
    build: .
    container_name: airdcpp-bridge
    ports:
      - 8000:8000
    environment:
      - AIRDCPP_URL=${AIRDCPP_URL}
      - AIRDCPP_USER=${AIRDCPP_USER}
      - AIRDCPP_PASS=${AIRDCPP_PASS}
      - AIRDCPP_API_KEY=${AIRDCPP_API_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
